name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Executa a cada 12 horas
  workflow_dispatch:        # Permite execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Gera a cobrinha de contribuições (SVG animado)
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: HeitFernandes
          svg_out_path: dist/github-contribution-grid-snake.svg
          graph_width: 800               # aumenta área visível
          color_snake: '#00ffcc'         # cor da cobrinha
          color_dots: '#444444'          # cor dos quadradinhos

      # Publica o SVG no GitHub Pages (branch "output")
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



